name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore src/DataGetterThingy/DataGetterThingy.csproj
    - name: Build
      run: dotnet build src/DataGetterThingy/DataGetterThingy.csproj --no-restore -c Release
    - name: Test
      run: dotnet test src/DataGetterThingy.sln --no-restore