name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore src/DataGetterThingy/DataGetterThingy.csproj
    - name: Build
      run: dotnet build src/DataGetterThingy/DataGetterThingy.csproj --no-restore -c Release
    - name: Publish Win x64
      run: dotnet publish -r win-x64 -c Release -p:PublishSingleFile=true --self-contained true
    - name: Publish OSX x64
      run: dotnet publish -r osx-x64 -c Release -p:PublishSingleFile=true --self-contained true
    - name: Publish Linux x64
      run: dotnet publish -r linux-x64 -c Release -p:PublishSingleFile=true --self-contained true